// <auto-generated />
using System;
using MapsVisualisation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapsVisualisation.Database.Migrations
{
    [DbContext(typeof(MapsVisualisationContext))]
    [Migration("20221114211701_AddedLocalImages")]
    partial class AddedLocalImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MapsVisualisation.Database.Models.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CollectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dpi")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("MapsVisualisation.Database.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("NELat")
                        .HasColumnType("float");

                    b.Property<double>("NELong")
                        .HasColumnType("float");

                    b.Property<double>("NWLat")
                        .HasColumnType("float");

                    b.Property<double>("NWLong")
                        .HasColumnType("float");

                    b.Property<string>("RegionIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SELat")
                        .HasColumnType("float");

                    b.Property<double>("SELong")
                        .HasColumnType("float");

                    b.Property<double>("SWLat")
                        .HasColumnType("float");

                    b.Property<double>("SWLong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("MapsVisualisation.Database.Models.Map", b =>
                {
                    b.HasOne("MapsVisualisation.Database.Models.Region", "Region")
                        .WithMany("Maps")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MapsVisualisation.Database.Models.Region", b =>
                {
                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
